### ISSUE TITLE
Crud Lista

### ISSUE THREAD

**Issue by adrianodemoura** [adrianodemoura/phpGridOld#1]
é preciso criar o Crud Lista, o layout desta action deve ficar no scaffolds do core, o formulário deve trabalhar todas as propriedades de cada campo.

**Comment by ThiagoSouzaMoura** [comment]
incrementei o total de registros no topo da lista.

**Comment by adrianodemoura** [comment]
está ficando bom, mas ainda falta:

Edição dos campos belongsTo e Habtm. O Sistema deve exibir um showModal para pesquisar o campo relacionado, quando o item for escolhido o sistema deve retornar apenas o id

Validação do campo. As validações devem seguir as propriedades do esquema, alguma propriedades podem ser verificadas via ajax.

Filtros. O Sistema deve permitir filtrar algumas campos, para isso deve ser colocado um selectBox para cada Filtro.

**Comment by ThiagoSouzaMoura** [comment]
favor testar a última implementação que fiz.

**Comment by adrianodemoura** [comment]
achei legal a idéia de encripitar os nomes dos campos da view, mas deu erro no validation da view, então tive que voltar pra deixar o nome mesmo. A idéia é boa mas vamos deixá-la mais para frente pra agilizar o termínio do milestone, o prazo tá apertado.

**Comment by adrianodemoura** [comment]
cadê a edição dos campos HABTM ? é preciso agilizar isso.

**Comment by adrianodemoura** [comment]
já tá saindo, estou criando o formulário ajax chamado form_habtm, tive uns probleminhas com o HTML que estava provocando erro na renderização do formulário, mas já está ok, o desenvolvimento continua.

**Comment by adrianodemoura** [comment]
a ajax form foi criado, ele pode melhor, mas vamos deixar pra próxima versão, o importante é que ele está funcional, o que pode ser feito depois é apenas enxugar o código, mas o importante já está bem.
