### ISSUE TITLE
Helper para data

### ISSUE THREAD

**Issue by adrianodemoura** [adrianodemoura/phpGridOld#15]
preciso de um bom helper pra ajudar na digitação de campos datas, tem que ser leve e funcional.

**Comment by ThiagoSouzaMoura** [comment]
ok, já implementei a primeira versão.

**Comment by adrianodemoura** [comment]
ficou bom, seria interessante incrementar um atributo pro model, aonde os valores dos minutos serão múltiplos de 5, assim o usuário irar escolher algo como 12:45.

**Comment by adrianodemoura** [comment]
ok, foi implementado direto no getInput, ficou bom, mas pode melhorar, vamos deixar pra próxima versão.
